---

- name: delete the default pool configuration file
  file:
    path: "{{ php_fpm_pool_conf_path }}/{{ php_fpm_default_pool.name }}"
    state: absent
  when:
    - php_fpm_default_pool.delete

- name: create pool configuration
  template:
    src: pool.conf.j2
    dest: "{{ php_fpm_pool_conf_path }}/{{ item.name }}.conf"
    backup: true
  with_items: "{{ php_fpm_pools }}"
  when:
    - php_fpm_pools | length > 0
  notify:
    restart php-fpm
