---
- name: Ensure php-fpm is started and enabled at boot (if configured).
  service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: yes
  when: php_enable_php_fpm | bool and ansible_distribution != "Debian"

# See: https://github.com/ansible/ansible/issues/22303
- name: Ensure php-fpm is started and enabled at boot (if configured, Debian).
  service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: yes
    use: service
  when: php_enable_php_fpm | bool and ansible_distribution == "Debian"

