---
#     - name: configure modules
#       php_modules:
#         php_modules: "{{ php_modules }}"
#         php_modules_path: "/etc/php/8.2/mods-available"
#         dest:
#           - /etc/php/8.2/fpm
#           - /etc/php/8.2/cli
#         # force: true
#       register: _modules_state
#       when:
#         - php_modules is defined
#
#     - name: d
#       debug:
#         msg: "{{ _modules_state }}"

- name: prepare
  ansible.builtin.include_tasks: prepare.yaml
  tags:
    - php-fpm

- name: detect available php version
  ansible.builtin.include_tasks: detect_php_version.yaml
  tags:
    - php-fpm

- name: install
  ansible.builtin.include_tasks: install.yaml
  tags:
    - php-fpm

- name: configure
  ansible.builtin.include_tasks: configure/main.yml
  tags:
    - php-fpm

- name: service
  ansible.builtin.include_tasks: service.yaml
  tags:
    - php-fpm

- name: ansible facts
  ansible.builtin.include_tasks: facts.yaml
  tags:
    - php-fpm

...
