---

- include: preparations.yml
  become: true
  tags:
    - preparations

- name: detect available php version
  include_tasks: detect_php_version.yml

- include_tasks: install.yml

- include_tasks: configure.yml
- include_tasks: dynamic-pools.yml
- include_tasks: service.yml
- include_tasks: facts.yml

...
