---

- include: preparations.yml
  become: true
  tags:
    - preparations

- name: detect available php version
  include_tasks: detect_php_version.yml

- include_tasks: 01-install.yml

- include_tasks: 10-configure.yml
- include_tasks: 15-dynamic-pools.yml
- include_tasks: 90-service.yml
