---

- name: prepare
  include_tasks: prepare.yaml
  tags:
    - php-fpm

- name: detect available php version
  include_tasks: detect_php_version.yaml
  tags:
    - php-fpm

- include_tasks: install.yaml
  tags:
    - php-fpm

- include_tasks: configure.yaml
  tags:
    - php-fpm

- include_tasks: dynamic-pools.yaml
  tags:
    - php-fpm

- include_tasks: service.yaml
  tags:
    - php-fpm

- include_tasks: facts.yaml
  tags:
    - php-fpm

...
