---
- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:
    - debug:
        msg:
          - "ansible_os_family                  : {{ ansible_os_family }}"
          - "ansible_distribution               : {{ ansible_distribution }}"
          - "ansible_distribution_major_version : {{ ansible_distribution_major_version }}"
          - "ansible_version                    : {{ ansible_version.full }}"
          - "ansible_python_version             : {{ ansible_python.version.major }}"

  roles:
    - role: nginx
