---
- name: prepare container
  hosts: all
  gather_facts: true

  vars:

    # nginx
    #
    nginx_server_tokens: "off"
    nginx_remove_default_vhost: true

    nginx_extra_http_options: |
      map_hash_max_size 128;
      map_hash_bucket_size 128;

    nginx_vhosts:
      - listen: 80
        server_name: _
        extra_parameters: |
          location / {
            root  /var/www;
            index index.php;
            location ~ ^/index\.php(.*)$ {
              fastcgi_index          index.php;
              fastcgi_read_timeout   600;
              fastcgi_pass           unix:/run/php/worker-01.sock;
              include fastcgi_params;
            }
          }

  pre_tasks:

    - debug:
        msg:
          - "ansible_os_family                  : {{ ansible_os_family }}"
          - "ansible_distribution               : {{ ansible_distribution }}"
          - "ansible_distribution_major_version : {{ ansible_distribution_major_version }}"
          - "ansible_version                    : {{ ansible_version.full }}"
          - "ansible_python_version             : {{ ansible_python.version.major }}"

  roles:
    - role: nginx
