---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''
  vars:

    php_fpm_pools:
      - name: worker-01
        user: "{{ php_fpm_pool_user }}"
        group: "{{ php_fpm_pool_group }}"
        listen.owner: "{{ php_fpm_pool_user }}"
        listen.group: "{{ php_fpm_pool_group }}"
        listen: "/run/php/$pool.sock"
        # static, dynamic or ondemand
        pm: ondemand
        pm.max_children: 10
        pm.start_servers: 4
        pm.min_spare_servers: 2
        pm.max_spare_servers: 6

    php_modules:
      - name: opcache
        enabled: true
        priority: 10
        content: |
          zend_extension=opcache.so
          opcache.enable=1
          opcache.enable_cli=1
          opcache.memory_consumption=128
          opcache.interned_strings_buffer=16
          opcache.max_accelerated_files=10000
          opcache.max_wasted_percentage=5
          opcache.validate_timestamps=1
          opcache.revalidate_path=0
          opcache.revalidate_freq=1
          opcache.max_file_size=0
      - name: pdo_mysql
        enabled: true
        priority: 20
        content: |
          extension=pdo_mysql.so
      - name: apcu
        enabled: false
        priority: 20
        content: |
          extension=apcu.so
          apc.shm_size=96M
          apc.enable_cli=0
          apc.rfc1867=1
      - name: gd
        enabled: true
        priority: 20
        content: |
          extension=gd.so
      - name: memcached
        enabled: false
        priority: 20
        content: |
          extension=memcached.so
      - name: pdo_mysql
        enabled: false
        priority: 30

  roles:
    - role: ansible-php
