---
extends: default
rules:
  line-length:
    max: 250
    level: warning
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  indentation:
    spaces: 2

ignore: |
  tests/
  molecule/
  .molecule/
  .travis.yml
