---

php_fpm_pools:
  - name: worker-01
    user: "{{ php_fpm_pool_user }}"
    group: "{{ php_fpm_pool_group }}"
    listen.owner: "{{ php_fpm_pool_user }}"
    listen.group: "{{ php_fpm_pool_group }}"
    listen: "{{ php_fpm_socket_directory }}/$poolck"
    # static, dynamic or ondemand
    pm: dynamic
    pm.max_children: 10
    pm.start_servers: 4
    pm.min_spare_servers: 2
    pm.max_spare_servers: 6
    env:
      MASTER: '"true"'
    php_flag:
      display_errors: "on"

php_modules:
  - name: opcache
    enabled: true
    priority: 10
    content: |
      zend_extension=opcache
      opcache.enable=1
      opcache.enable_cli=1
      opcache.memory_consumption=128
      opcache.interned_strings_buffer=16
      opcache.max_accelerated_files=10000
      opcache.max_wasted_percentage=5
      opcache.validate_timestamps=1
      opcache.revalidate_path=0
      opcache.revalidate_freq=1
      opcache.max_file_size=0
  - name: pdo_mysql
    enabled: true
    priority: 20
    content: |
      extension=pdo_mysql
  - name: apcu
    enabled: false
    priority: 20
    content: |
      extension=apcu
      apc.shm_size=96M
      apc.enable_cli=0
      apc.rfc1867=1
  - name: gd
    enabled: true
    priority: 20
    content: |
      extension=gd
  - name: memcached
    enabled: false
    priority: 20
    content: |
      extension=memcached
  - name: xmlrpc
    enabled: "{{ 'false' if ansible_os_family | lower == 'archlinux' else 'true' }}"
    priority: 20
    content: |
      extension=xmlrpc
  - name: sqlite3
    enabled: false
    priority: 20
    content: |
      extension=sqlite3
      extension=pdo_sqlite
  - name: pdo_mysql
    enabled: false
    priority: 30

php_packages:
  - php-gd
  - php-intl
  # - php-sqlite

# OBSOLETE
# replaced by `php_packages`
php_custom_packages: []
