---

- name: debian repositories
  ansible.builtin.include_tasks: repositories/debian.yml
  when:
    - ansible_os_family | lower == 'debian'

- name: update package cache
  become: true
  ansible.builtin.package:
    update_cache: true

...
